### ISSUE TITLE
First Implimentation of a GOC API

### ISSUE THREAD

**Issue by samperd** [wet-boew/wet-boew-api-standards#22]
Hey Folks,

In the spirit of Agile I am wondering if there is an appetite to propose a first implementation of a unified GOC API end point. Let me know if this is off topic or already being explored.

The proposal would be to work with SSC (Shared Services Canada) to stand up an API proxy. This proxy would provide a single end point that people can connect to (eg http://data.gc.ca/api).

This nice part is that SSC would be the host and have to relatively little development.

Employing an API proxy already deployed in large Open Stack environments we can implement something quite quickly. I propose that we can explore Open Repose http://www.openrepose.org/ which is part of the Open Stack () and already heavily used, developed and supported.

The idea is that each API owner would need to configure the reverse proxy to consume their own in house API.

This would be a quick win because we can standardize (and evolve the standard) by controlling the requests coming in and leave it to the departments to configure their own API.

This should be a fairly simple activity with a quick(ish) turn around time. (3 months for first launch and 3 API's?).

If this activity already belongs with someone within GOC please point me in the right direction. This would be fun to help advise.

Cheers

**Comment by chrismajewski** [comment]
Hopefully the MWS can find a buyer for application migration using this as a starting point.

This will happen through the TBS::CIOB::MWS Config team if so.
